import 'package:estreet/pages/sliderBanners.dart';
import 'package:flutter/material.dart';

import '../footer.dart';
import '../header.dart';

class termsAndConditions extends StatelessWidget {
  double minheight = 45;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        shrinkWrap: true,
        children: [
          header(),
          BannerSlider(),
          Padding(
            padding: const EdgeInsets.all(62.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
                SizedBox(
                  height: minheight,
                ),
                Text(
                  'Terms and Conditions',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                SizedBox(
                  height: minheight,
                ),
                Text('Welcome to Estreetmart internal website for vendors, where you can obtain information to' +
                    'assist with managing your relationship with estreetmart.sg Services, Inc., and its affiliates' +
                    '(each and collectively, “Estreetmart”, “we”, “us” or “our”). Any person or entity (“Vendor”, “you”' +
                    'or “your”) who wants to supply Products (as defined in Section 1) to Estreetmart or access or' +
                    'use this website must accept these Vendor Terms and Conditions (“Agreement”) without' +
                    'change. BY REGISTERING FOR OR OTHERWISE USING THIS WEBSITE, YOU ON BEHALF OF' +
                    'YOURSELF AND THE ENTITY THAT YOU REPRESENT, AGREE TO BE BOUND BY ALL TERMS AND' +
                    'CONDITIONS OF THIS AGREEMENT, INCLUDING ALL TERMS AND CONDITIONS' +
                    'INCORPORATED BY REFERENCE; REPRESENT AND WARRANT THAT YOU ARE EXPRESSLY' +
                    'AUTHORIZED TO BIND VENDOR TO THIS AGREEMENT.' +
                    '\nThese ‘Conditions of Use’ constitute an electronic record within the meaning of the applicable' +
                    'law. This electronic record is generated by a computer system and does not require any' +
                    'physical or digital signatures.'),
              ],
            ),
          ),
          footer(),
        ],
      ),
    );
  }
}
